name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools build twine

      # Import GPG key
      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch
          gpg --list-keys
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      # Build the package
      - name: Build the package
        run: python -m build

      # Sign the package
      - name: Sign the package
        run: |
          for file in dist/*.{tar.gz,whl}; do
            gpg --default-key 3D2E02E67B693A84F438D28584EDD2EE0A9C1182 --detach-sign -a "$file";
          done

      # Upload to PyPI
      - name: Publish to PyPI
        run: |
          python -m twine upload --sign --identity 3D2E02E67B693A84F438D28584EDD2EE0A9C1182 dist/*
